In [44]:
import numpy as np
numpy.version.full_version

'1.21.2'

In [45]:
a = np.array([0, 1, 2,3, 4, 5])
print(a.ndim) # Массив одномерный(ndim показывает мерность массива)
a.shape

1


(6,)

In [46]:
b = a.reshape((3, 2)) # Сделаем массив двумерным.
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
b[1][0] = 77 # Копирование не производится.
print(b, a, sep = "\n") # Нужно использовать copy() для копирования.

[[ 0  1]
 [77  3]
 [ 4  5]]
[ 0  1 77  3  4  5]


In [48]:
d = np.array([1, 2, 3, 4, 5])
d *= 2 # Тоже справедливо и для других операций.
d # Умножение всех эл. на число.

array([ 2,  4,  6,  8, 10])

In [49]:
a[np.array([2, 3, 4])] # Доступ к нескольким индексам

array([77,  3,  4])

In [50]:
a > 4

array([False, False,  True, False, False,  True])

In [51]:
print(a[a>4]) # Вывести эл-ты удовлетворяющие условию.
a[a>4] = 4 # всем эл-там больше 4 присовоить 4.
a

[77  5]


array([0, 1, 4, 3, 4, 4])

*Проверим скорость numpy*

In [55]:
import timeit

normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))', number = 10000)

naive_np_sec = timeit.timeit('sum(na*na)',
                              setup = "import numpy as np; na = np.arange(1000)",
                              number = 10000)

good_np_sec = timeit.timeit('na.dot(na)', # Складываем все элементы массива
                             setup = "import numpy as np; na = np.arange(1000)",
                             number = 10000)

In [56]:
print(f"Normal Python: {normal_py_sec}")
print(f"Naive NumPy: {naive_np_sec}")
print(f"Good NumPy: {good_np_sec}")

Normal Python: 0.8955531000001429
Naive NumPy: 1.007100800000444
Good NumPy: 0.01472849999936443


In [59]:
import scipy, numpy
scipy.version.full_version
scipy.dot is numpy.dot

False